#!/usr/bin/env node
"use strict";
// Rewrites src/shell/i18n.js and src/shell/settings-i18n.js keeping only KEEP_LANGS and dropping removed-subsystem keys.
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const KEEP_LANGS = ["en", "zh", "zh-TW"];
const BANNED = /telegram|feishu|lark|slack|discord|remoteSsh|remote-ssh|recap|kimi|tutorial|mobile|wayland|appimage|winget/i;
const root = path.join(__dirname, "..");

function trimDict(dict) {
  const out = {};
  for (const lang of KEEP_LANGS) {
    out[lang] = {};
    for (const [k, v] of Object.entries(dict[lang] || {})) if (!BANNED.test(k)) out[lang][k] = v;
  }
  return out;
}

// JSON.stringify drops function-valued entries (count formatters like
// doctorAgentSummaryOk / toastCodexPetsRefreshOk), so emit their source instead.
// Source-level assertions elsewhere match bare `key:`, so quote only what has to be.
const key = (k) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k));

function serializeDict(dict, pad) {
  const outer = " ".repeat(pad);
  const lang = " ".repeat(pad + 2);
  const entry = " ".repeat(pad + 4);
  const langs = Object.entries(dict).map(([code, entries]) => {
    const body = Object.entries(entries)
      .map(([k, v]) => `${entry}${key(k)}: ${typeof v === "function" ? String(v) : JSON.stringify(v)},`)
      .join("\n");
    return `${lang}${key(code)}: {\n${body}\n${lang}},`;
  });
  return `{\n${langs.join("\n")}\n${outer}}`;
}

const i18nPath = path.join(root, "src", "shell", "i18n.js");
const i18n = trimDict(require(i18nPath).i18n);
fs.writeFileSync(i18nPath, `"use strict";

// Generated by scripts/trim-i18n.js from the upstream string table. Edit the JSON block, not the tail.
const i18n = ${serializeDict(i18n, 0)};

const SUPPORTED_LANGS = Object.freeze(${JSON.stringify(KEEP_LANGS)});

function createTranslator(getLang) {
  if (typeof getLang !== "function") {
    throw new TypeError("createTranslator(getLang): getLang must be a function");
  }
  return function t(key) {
    const lang = getLang();
    const dict = i18n[lang] || i18n.en;
    return dict[key] || key;
  };
}

module.exports = { i18n, SUPPORTED_LANGS, createTranslator };
`);

const sPath = path.join(root, "src", "shell", "settings-i18n.js");
const sandbox = {};
vm.runInNewContext(fs.readFileSync(sPath, "utf8"), { globalThis: sandbox });
const { STRINGS, MAINTAINERS, CONTRIBUTORS } = sandbox.DuckSettingsI18n;
fs.writeFileSync(sPath, `"use strict";

// Generated by scripts/trim-i18n.js from the upstream string table.
(function initSettingsI18n(root) {
  const STRINGS = ${serializeDict(trimDict(STRINGS), 2)};
  const MAINTAINERS = ${JSON.stringify(MAINTAINERS)};
  const CONTRIBUTORS = ${JSON.stringify(CONTRIBUTORS)};
  root.DuckSettingsI18n = { STRINGS, MAINTAINERS, CONTRIBUTORS };
})(globalThis);
`);
console.log("i18n trimmed:", KEEP_LANGS.join(","), "| settings keys:", Object.keys(trimDict(STRINGS).en).length);
